FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src

COPY Anime.slnx .
COPY Anime.API/*.csproj Anime.API/
COPY Anime.BLL/*.csproj Anime.BLL/
COPY Anime.DAL/*.csproj Anime.DAL/
COPY IntegrationTests/*.csproj IntegrationTests/
COPY UnitTests/*.csproj UnitTests/

RUN dotnet restore

COPY . .

WORKDIR /src/Anime.API
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS runtime
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Anime.API.dll"]